### ISSUE TITLE
Support for realtime updates, without reloads?

### ISSUE THREAD

**Issue by 0thernet** [vnglst/svelte-gundb-chat#2]
Hi! I'm very new to dapps, GUN, (and also Svelte), but I've been vaguely interested in both, and happened to find this project from @marknadal's tweet.

I got this project up and running super quickly, and it's gotten me super excited about learning more about GUN and building decentralized apps. Thanks for putting together such a polished chat dapp and sharing it!

I know you put this together very quickly so it's very early stage, but I was wondering whether you've thought about realtime updates over webRTC, and how you'd go about supporting that? (When I try running this in two browser windows, I have to refresh to get updates).

I _kinda_ expected this to work with GUN out of the box.

https://github.com/amark/gun/issues/766

**Comment by vnglst** [comment]
Thanks, really appreciate you taking the time to say this! 😚

I’m also pretty new to this, I’ve been following gundb for some time now and finally got around to experimenting with it. I really liked how easy it was to integrate with it. Just a few lines of code and it just worked!

Realtime updates should work, I think currently over websockets. There’s a tweet with a demo from me somewhere that shows that.

Using webrtc would be really cool though, that would make the gun nodes/servers even less important. I didn’t know gun offered that, will have to look into that soon, see if that works.

**Comment by vnglst** [comment]
I just checked and you're right! Realtime updates are not working right now. Maybe because I upgraded to a newer version of gundb? For now I'm gonna revert to the last working version I had. 

Maybe @amark knows why realtime updates are not working?

**Comment by vnglst** [comment]
Fixed in this commit: aaa8d4407650ecea8f11769b2588a82d6ceaf1f6

I will open a PR with the upgrade so I can keep track of this issue and see if it's fixed in a later release of gun.

**Comment by 0thernet** [comment]
awesome, thanks for the update! I was a bit surprised by this not being realtime by default, good to know it actually is supported by default in gundb ✨ 

I put together this quick writeup on my browsing through decentralized tech things this weekend (which eventually led me to gundb and this project). 

Sharing here, hopefully it's useful to fellow travelers :) 🌄 

https://www.notion.so/Decentralized-tech-research-log-ec41e3727abc4bd485c7bcfe4f53b275
