### ISSUE TITLE
question: how did you deploy your server?

### ISSUE THREAD

**Issue by 0thernet** [vnglst/svelte-gundb-chat#20]
Hi again @vnglst ! 

I've been trying to set up a gundb server on Heroku (the hapi server you have here), but I've been having trouble getting it to work (I'm seeing websocket handshake errors). 

I noticed you had a comment:

```
// "https://gunjs.herokuapp.com/gun", // Don't use, unstable
```

Could you share what you ended up using to deploy your server at `https://phrassed.com/gun`? 

Thanks! 🙏

**Comment by vnglst** [comment]
Hi Ben,

I deployed it on a Digital Ocean virtual server. It's their smallest instance and on it I just do a `node server.js` behind a reverse proxy (using Caddy for that). Let me know if you want more information on how to do that.

I don't know much about setting up gundb on Heroku. The problem could be that the free instances of Heroku are put to sleep? But should work otherwise, seems to be the recommended approach.

**Comment by 0thernet** [comment]
Thanks @vnglst , that's helpful! I wasn't able to set up a non-flaky Heroku relay, so I went with a similar approach to you, using https://render.com/ on their smallest instance. The "disks" option that Render has seems useful – I enabled that, and theoretically that means my GunDB relay can persist data to disk too (which isn't possible with a service like Heroku, without setting up an S3 adapter...)

Sharing some notes on my learnings:

> Gun requires a **signaling server** to coordinate where non-IPv6 peers like a browser are. Relay peers can also store/sync data. If you’re using Heroku (or a similar free service) to run your NodeJS peer, you likely won’t be able to use file system storage because the [Heroku filesystem is ephemeral](https://devcenter.heroku.com/articles/dynos). File system storage is the default, and fine for development. You can [use S3 for storage](https://gun.eco/docs/Using-Amazon-S3-for-Storage) by providing some environment variables.

>  Gun uses **websockets** for real-time replication across peers. **webRTC** is disabled by default, but can be enabled with an optional lib. Theoretically, webRTC could enable using GunDB without a signaling server. However, webRTC is flaky, so even with webRTC enabled, GunDB still defaults to the relay peer unless you make some tweaks (see this [stackoverflow answer](https://stackoverflow.com/questions/51913962/how-to-use-a-gun-server-as-a-relay-only/52014080#52014080)). If peers fail to establish webRTC connection, they can use daisy-chain ad-hoc mesh networking (DAM), but that requires a signaling server.

**Comment by vnglst** [comment]
Nice write up! I did not know begin, what are you paying for their smallest instance with storage?
